### ISSUE TITLE
UnityFramework/Unityframework.h file not found on build 

### ISSUE THREAD

**Issue by abhijeetnaik2** [asmadsen/react-native-unity-view#1]
I am getting the following error: 
I followed all the steps mentioned 

![image](https://user-images.githubusercontent.com/30176282/72302035-c2d1b280-368e-11ea-8b01-3b7d2f8e0cf6.png)

![image](https://user-images.githubusercontent.com/30176282/72302113-02000380-368f-11ea-832e-3a11afb06e5c.png)

**Comment by asmadsen** [comment]
Hi, I have only tested to run it on a real device, if you don't have one available you can try to select the "Simulator SDK" in iOS player settings in unity before exporting again

**Comment by ziyoshams** [comment]
I seem to have this issue for Profile builds.

**Comment by ziyoshams** [comment]
> I seem to have this issue for Profile builds.

@asmadsen have encountered this before?
