### ISSUE TITLE
Could not find unity classes

### ISSUE THREAD

**Issue by MaksymMalin** [asmadsen/react-native-unity-view#14]
Hello i have created new create-react-native app but cannot got error after following instructions.

**Comment by MaksymMalin** [comment]
Could not find :unity-classes:.
     Required by:
         project :@asmadsen_react-native-unity-view

**Comment by luojiong** [comment]
I ran into this problem at the beginning. I put my unityexport in the Android directory and it’s no problem. I don’t know if this will help you. @MaksymMalin

**Comment by MaksymMalin** [comment]
Thanks for your attention it is solved  @luojiong with latest npm and latest create-react-native-app
