### ISSUE TITLE
Question! @react-native-community/async-storage could not be found within the project or in these directories:   node_modules/@react-native-community

### ISSUE THREAD

**Issue by ziyoshams** [asmadsen/react-native-unity-view#2]
Does anyone know why I get `@react-native-community/async-storage` errors from the packager after installing this package?
Here is the error message while loading JS in the packager.

```
@react-native-community/async-storage could not be found within the project or in these directories:
  node_modules/@react-native-community
```

I have cleared every cache possible and re-installed hundreds of time. Nothing seems to fix this error.

Wondering if anyone else had the same problem.

**Comment by asmadsen** [comment]
This library has no reference to `@react-native-community/async-storage` so it shouldn't have anything to do with adding this library.
You can try to run `yarn list` or `npm ls` and check if there is any of your dependencies that lists a dependency on `@react-native-community/async-storage`. An easier solution might be to delete the `yarn.lock` or `package-lock.json` and  `node_modules` based on the `package.json` instead.

**Comment by ziyoshams** [comment]
@asmadsen Thank you. It was my own fault. I  blacklisted the `unity` folder for the metro bundler in `metro.config.js`. Turns out that it matched `community` part of the `react-native-community` folder which contains `unity`, therefore blacklisting all react-native-community modules.
