### ISSUE TITLE
iOS Archive build: UnityFramework/UnityFramework.h file not found

### ISSUE THREAD

**Issue by englandrp** [asmadsen/react-native-unity-view#4]
Generally this works great, thank you. I have hit a bit of a brick wall on the final straight though....

I can build directly to a device no problem but upon building to archive I'm getting:

`{...}/node_modules/@asmadsen/react-native-unity-view/ios/UnityUtils.h:2:9: 'UnityFramework/UnityFramework.h' file not found`

Presumably a setting in the target that's missing, but having tried a few things I'm wondering if you got that far and, if so, how you made it build?

**Comment by englandrp** [comment]
Turns out it's this setting - needed to be unchecked in order for archive to work. Didn't affect build to device...

![image](https://user-images.githubusercontent.com/368451/77479912-9ec1e880-6e18-11ea-9d47-aaabcbdfab21.png)

**Comment by shercoder** [comment]
@englandrp So running into this issue as well. I've set the Target SDK to be `Device SDK` and running the app on device. So your solution fixes this issue but if you clean install all modules or lets say another developer wants to use run the code they run into the same error again unless they manually use your solution. 

Have you been able to figure out a permanent solution for this? 
Maybe @asmadsen know something about it?

**Comment by shercoder** [comment]
ok so figured it out. Couple of things needed to happen:
1. Our own project was not leveraging "parallelize build" option. I turned that on.
2. I added UnityFramework.framework under Embedded Frameworks originally since using Xcode 10 and it has slightly different interface than Xcode 11. So I removed it from Embedded Frameworks. Then followed this guide to resolve my issue https://stackoverflow.com/a/43197278/9487378

**Comment by hellovoidworld** [comment]
@englandrp nice! It works, thx very much!

**Comment by miketalbott** [comment]
Unfortunately, I have not been able to resolve this in Xcode 12. I followed the guide linked above, but still get the "UnityFramework/UnityFramework.h file not found".

One piece of information to add: I successfully archived the example unity project. I added ARFoundation and ARKit to the unity project (no other changes) and now it won't build the archive.

**Comment by KovtunOleg** [comment]
The same issue for us too, everything works for debug build, but when we try to make an archive we get this error.

**'UnityFramework/UnityFramework.h' file not found**, aslo tried all suggestions above without a luck (

What worked for us was to set **Pods** and **Runner** projects deployment targets to 12.0 (minimum iOS supported on Xcode 12)

<img width="1270" alt="Снимок экрана 2020-10-16 в 22 09 28" src="https://user-images.githubusercontent.com/1674694/96299179-4e041e00-0ffc-11eb-88b6-061e6b94225c.png">

And set `Build Active Architecture Only` to YES for **Pods** project.

<img width="1108" alt="Снимок экрана 2020-10-16 в 22 07 45" src="https://user-images.githubusercontent.com/1674694/96299022-109f9080-0ffc-11eb-9192-527b04eaba7b.png">

**Comment by MugOfPaul** [comment]
An alternative to changing "Build Active Architecture Only" is to put x86_64 in the Excluded Architectures list. I believe this will resolve your AR issue @miketalbott

**Comment by shercoder** [comment]
This is the solution that is simple and works flawlessly for anyone still looking: https://github.com/asmadsen/react-native-unity-view/issues/8#issuecomment-728683394

**Comment by DGKall** [comment]
> The same issue for us too, everything works for debug build, but when we try to make an archive we get this error.
> 
> **'UnityFramework/UnityFramework.h' file not found**, aslo tried all suggestions above without a luck (
> 
> What worked for us was to set **Pods** and **Runner** projects deployment targets to 12.0 (minimum iOS supported on Xcode 12)
> 
> <img alt="Снимок экрана 2020-10-16 в 22 09 28" width="1270" src="https://user-images.githubusercontent.com/1674694/96299179-4e041e00-0ffc-11eb-88b6-061e6b94225c.png">
> 
> And set `Build Active Architecture Only` to YES for **Pods** project.
> 
> <img alt="Снимок экрана 2020-10-16 в 22 07 45" width="1108" src="https://user-images.githubusercontent.com/1674694/96299022-109f9080-0ffc-11eb-9192-527b04eaba7b.png">

Thanks for sharing!
