### ISSUE TITLE
ld: symbol(s) not found for architecture arm64  . also experienced issue for arm7

### ISSUE THREAD

**Issue by bincy-baby** [asmadsen/react-native-unity-view#42]
Ld /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/armv7/Binary/UnityFramework normal armv7 (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/administrator/.jenkins/workspace/action_ar_ios_app_pool_upload_autobuild/mobileapp/ActionAR/ios/UnityExport
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target armv7-apple-ios10.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.2.sdk -L/Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/BuildProductsPath/Release-iphoneos -L/Users/administrator/.jenkins/workspace/action_ar_ios_app_pool_upload_autobuild/mobileapp/ActionAR/ios/UnityExport/Libraries -F/Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/BuildProductsPath/Release-iphoneos -filelist /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-armv7.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/BuildProductsPath/Release-iphoneos -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -framework CloudKit -weak_framework Metal -weak_framework GameController -Xlinker -dependency_info -Xlinker /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework_dependency_info.dat -o /Users/administrator/Library/Developer/Xcode/DerivedData/ActionAR-etqwbnfrpvcjklhagwwkknyzyvwh/Build/Intermediates.noindex/ArchiveIntermediates/ActionAR/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/armv7/Binary/UnityFramework
Undefined symbols for architecture armv7:
  "_onUnityMessage", referenced from:
      _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4 in Assembly-CSharp1.o
     (maybe you meant: _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can anyone help with this issue?

**Comment by muhammadhurali** [comment]
@bincy-baby Did you find any working solution?

**Comment by nimiththomas** [comment]
@muhammadhurali  in the xcodepostbuild.cs file replace
#if UNITY_IOS     
with

#if UNITY_ANDROID
#else

This really fixed the problem for me.I think it has something to do with unity not compiling #if UNITY_IOS statement for some reason and all the commands in the xcodepostbuild.cs are not executed.Changing the if statement worked for me
