### ISSUE TITLE
UnityExport file size for iOS too big

### ISSUE THREAD

**Issue by shhhiiiii** [asmadsen/react-native-unity-view#65]
Need help how to reduce the file size of unity export for ios?
I have a simple unity project and when i build a unity export for ios it way too big nearly 1G.

Mostly because of libraries folder alone have 700MB

<img width="672" alt="Screenshot 2021-09-09 at 17 42 33" src="https://user-images.githubusercontent.com/44385931/132662957-ce15cbcf-4a47-4bd5-b395-d5897dfe6bb9.png">

**Comment by pjc0247** [comment]
https://docs.unity3d.com/Manual/ReducingFilesize.html

**Comment by shhhiiiii** [comment]
@pjc0247 Thank you for your reply. I appreciate it.
 I have tried and optimize most of my UI game asstes and even avoided using Generics calls. The unity file it self is small but my problem is that when it is exported into ios.

I have found this disscusion about the unity ios export.
https://forum.unity.com/threads/unity-ios-exported-xcode-project-is-too-huge.1029433/
it doesn't give the exact answer on how to optimize but the explaination make sense.

**Comment by pjc0247** [comment]
@shhhiiiii Did you checked your build log? it shows every resource's size like below:

![image](https://user-images.githubusercontent.com/1961216/133414509-8a9a12da-bb73-4567-afe9-e05db6242f47.png)

Packaged size is larger than original resources. becuase they are not `png` or `jpg` anymore. They converted into GPU compatible compression format which means more filesize.
So, comparing sizes between original project and built result is mostly useless.

Second reason,
https://forums.expo.dev/t/ipa-file-is-too-large/11921
https://stackoverflow.com/a/47530132
```
Although size of the IPA is big, once uploaded to App Store the download size for final users is much smaller. (250 MB vs 30 MB)
```
```
Yes thats absolutely normal. App thining is done at the app store level. Whenever you create .ipa file it consists of all the configurations needed for all the devices it supports. But whenever a user will download the app from the store he/she will get app size of lesser size , as only the relevant config would have been installed.
```

it's pretty normal that iOS program size is larger than Android's.

**Comment by shhhiiiii** [comment]
@pjc0247 yeah I have checked build logs and its show that libraries folders biggest file size.
( libil2cpp.a and libiPhone-lib.a) 


Yeah I have figure out that there's nothing I can do on reducing the file size.
My problem is that I cant commit iOs unity export in our repo since it is way to big. 
So I just have an alternative solution on how I can transfer unity export folder in our repo. 

Thank again for your response, :)
