### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by khacbac** [asmadsen/react-native-unity-view#71]
![Screen Shot 2021-09-29 at 11 24 36](https://user-images.githubusercontent.com/19282284/135203381-11f01bd8-b6da-4840-9d8b-5e30e4342c8f.png)

 Hi all, my unity project is using an external library NatCorder. After reactnative - export and then Build app,
 I got an error like this. Can anyone help me?. I have searched and tried many ways but to no avail. By the way, when I try with another Unity project that doesn't use NatCorder, it works. So I guess error when adding external library like NatCorder. Thanks a lot

**Comment by gambit19** [comment]
Hi @asmadsen We are also facing this exact same issue with an external library. Can anyone guide us on how to fix this issue?

Error: 
dyld: Library not loaded: @rpath/Sentry.framework/Sentry

**Comment by khacbac** [comment]
> Hi @asmadsen We are also facing this exact same issue with an external library. Can anyone guide us on how to fix this issue?
> 
> Error: dyld: Library not loaded: @rpath/Sentry.framework/Sentry

**Comment by khacbac** [comment]
> Hi @asmadsen We are also facing this exact same issue with an external library. Can anyone guide us on how to fix this issue?
> 
> Error: dyld: Library not loaded: @rpath/Sentry.framework/Sentry

I followed this Link and has fixed. You can try
https://github.com/juicycleff/flutter-unity-view-widget/issues/314

**Comment by ahmetardal** [comment]
> > Hi @asmadsen We are also facing this exact same issue with an external library. Can anyone guide us on how to fix this issue?
> > Error: dyld: Library not loaded: @rpath/Sentry.framework/Sentry
> 
> I followed this Link and has fixed. You can try [juicycleff/flutter-unity-view-widget#314](https://github.com/juicycleff/flutter-unity-view-widget/issues/314)

@khacbac Which part did exactly helped you? Thanks.

**Comment by khacbac** [comment]
this part:
https://github.com/juicycleff/flutter-unity-view-widget/issues/314#issuecomment-785302253

**Comment by ahmetardal** [comment]
@khacbac Thank you.
