### ISSUE TITLE
C'ant build my project for android

### ISSUE THREAD

**Issue by finbuld** [asmadsen/react-native-unity-view#73]
It's my first time using this package and I'm having this error on unity 2020.3.22f1

`InvalidOperationException: The build cannot be appended.
UnityEditor.BuildPipeline.BuildPlayer (System.String[] scenes, System.String locationPathName, System.String assetBundleManifestPath, UnityEditor.BuildTargetGroup buildTargetGroup, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options, System.String[] extraScriptingDefines) (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:329)
UnityEditor.BuildPipeline.BuildPlayer (UnityEditor.BuildPlayerOptions buildPlayerOptions) (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:295)
UnityEditor.BuildPipeline.BuildPlayer (System.String[] levels, System.String locationPathName, UnityEditor.BuildTarget target, UnityEditor.BuildOptions options) (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:290)
Build.DoBuildAndroid (System.String buildPath) (at Assets/Scripts/Editor/Build.cs:44)
Build.DoBuildAndroidLibrary () (at Assets/Scripts/Editor/Build.cs:23)`

**Comment by DavidCotovanu** [comment]
@finbuld Did you solve this? If you did, how?

For anyone stumbling on this, the solution is here #25
