### ISSUE TITLE
iOS build fail

### ISSUE THREAD

**Issue by Natkarock** [asmadsen/react-native-unity-view#8]
Hello! When I try build ios app, I have an error in UnityUtils.h: **'UnityFramework/UnityFramework.h' file not found**
<img width="871" alt="Screenshot 2020-07-04 at 15 18 49" src="https://user-images.githubusercontent.com/13661564/86512329-dbcf4b00-be09-11ea-8b1b-17e657d3a5fa.png">

React-native version: 0.62.2

**Comment by eumakarov** [comment]
@Natkarock, did you find a solution?

**Comment by Natkarock** [comment]
No, i think it is because my rn version 0.62. What is your rn version?

ср, 22 июл. 2020 г., 12:04 Evgeniy Makarov <notifications@github.com>:

**Comment by eumakarov** [comment]
Same version. Do you use an emulator? If so, then it looks like the original fork does not support emulators.
![Screenshot 2020-07-22 at 16 21 53](https://user-images.githubusercontent.com/39123355/88181758-f726bc80-cc37-11ea-8a55-eebada1c09ea.png)
I'll run code on real device later on. It may be emulator-only error

**Comment by chiechelski** [comment]
@Natkarock and @eumakarov , did you guys find any solution for this issue?

**Comment by RemyLivewall** [comment]
If you are trying to archive the build check the scheme settings for your target. You should add the UnityFramework to the step above your app to make sure it gets properly compiled when you are archiving the application.

**Comment by mrstluo** [comment]
same issue,have any solution?

**Comment by jagg18** [comment]
has anyone solved this issue?

**Comment by miketalbott** [comment]
I am also having this issues. 

This seems to be the same or related to the [closed issue](https://github.com/asmadsen/react-native-unity-view/issues/4) But I've followed all advice in that post and still get the error. the issue for me began when I added ARFoundation and ARKit to the unity project.

**Comment by wintermute-ik** [comment]
> I am also having this issues.
> 
> This seems to be the same or related to the [closed issue](https://github.com/asmadsen/react-native-unity-view/issues/4) But I've followed all advice in that post and still get the error. the issue for me began when I added ARFoundation and ARKit to the unity project.

I also have problems with ARFoundation integration. Tell me please, did you manage to solve them?

**Comment by ahmetardal** [comment]
In Xcode go to `Edit Scheme->Build`. Add `UnityFramework` to Targets list. It should be the first item in the list. This makes sure that `UnityFramework.framework` is generated and `UnityFramework/UnityFramework.h` is available before the main project is built.

![Screen Shot 2020-11-17 at 07 39 29](https://user-images.githubusercontent.com/435000/99347626-95562680-28a8-11eb-8b63-0335defc352b.png)

**Comment by syeddanishdev** [comment]
Issue 'UnityFramework/UnityFramework.h' file not found

Detail: iOS Build for Simulator Failed UnityFramework.h not found in UnityUtils.H

Build for Simulator has exported project by following all steps from custom package import to build settings, has reconfigured iOS project as well in Xcode for the framework and other schema settings but it fails to build.

Unity Editor 2019.3

Xcode 12.4
<img width="1138" alt="Screenshot 2021-02-16 at 14 46 14" src="https://user-images.githubusercontent.com/38407430/108071931-98f37800-7066-11eb-8f2a-eb4d9ea1b958.png">

**Comment by shercoder** [comment]
> In Xcode go to `Edit Scheme->Build`. Add `UnityFramework` to Targets list. It should be the first item in the list. This makes sure that `UnityFramework.framework` is generated and `UnityFramework/UnityFramework.h` is available before the main project is built.
> 
> ![Screen Shot 2020-11-17 at 07 39 29](https://user-images.githubusercontent.com/435000/99347626-95562680-28a8-11eb-8b63-0335defc352b.png)

This is the solution, folks. I have had this error for months and had to manually build the UnityFramework before building the app. This solution is simple and works. 

Thanks @ardalahmet

**Comment by klokie** [comment]
Hi, I wasn't able to get that recommendation to work. Even after hard-coding relative paths within `ios/UnityUtils.h` and `ios/RNUnityViewManager.h` as well as the `ios/UnityExport/UnityFramework/UnityFramework.h` and `ios/UnityExport/Classes/UnityAppController.h` files at the root of my project in order to fix the original error, the linker now complains:
`ld: framework not found UnityFramework`. Hoping someone here knows how to fix this. Thanks!

**Comment by ArnauKokoro** [comment]
Same here, the recommendation is not working for me either. Is there other solution? Thanks!

**Comment by Natkarock** [comment]
> Same here, the recommendation is not working for me either. Is there other solution? Thanks!

https://github.com/asmadsen/react-native-unity-view/issues/8#issuecomment-784393444 -this should work

**Comment by ArnauKokoro** [comment]
Sorry, this is the recommendation but is not working for me. Thanks!

- I do add at first position the UnityFramework on my app scheme build
- I do build UnityFramework before building my app

And still getting the same error. Thanks!!

**Comment by Natkarock** [comment]
> Sorry, this is the recommendation but is not working for me. Thanks!
> 
> * I do add at first position the UnityFramework on my app scheme build
> * I do build UnityFramework before building my app
> 
> And still getting the same error. Thanks!!

<img width="761" alt="Screenshot 2021-04-30 at 11 46 01" src="https://user-images.githubusercontent.com/13661564/116671551-bbc8d380-a9a9-11eb-9cb6-c2a2ca4ec54b.png">

Try add step **Build Phases -> Link Binary with Libraries** before  **Copy Bundle Resources** step

**Comment by ArnauKokoro** [comment]
> > Sorry, this is the recommendation but is not working for me. Thanks!
> > 
> > * I do add at first position the UnityFramework on my app scheme build
> > * I do build UnityFramework before building my app
> > 
> > And still getting the same error. Thanks!!
> 
> <img alt="Screenshot 2021-04-30 at 11 46 01" width="761" src="https://user-images.githubusercontent.com/13661564/116671551-bbc8d380-a9a9-11eb-9cb6-c2a2ca4ec54b.png">
> 
> Try add step **Build Phases -> Link Binary with Libraries** before **Copy Bundle Resources** step

Many Thanks!! I have it like this already. Still having the error.

When is building I can see UnityFrameworks builds first and it fails with the error at last when the build is almost finished.

Thanks!!

**Comment by Natkarock** [comment]
> > > Sorry, this is the recommendation but is not working for me. Thanks!
> > > 
> > > * I do add at first position the UnityFramework on my app scheme build
> > > * I do build UnityFramework before building my app
> > > 
> > > And still getting the same error. Thanks!!
> > 
> > 
> > <img alt="Screenshot 2021-04-30 at 11 46 01" width="761" src="https://user-images.githubusercontent.com/13661564/116671551-bbc8d380-a9a9-11eb-9cb6-c2a2ca4ec54b.png">
> > Try add step **Build Phases -> Link Binary with Libraries** before **Copy Bundle Resources** step
> 
> Many Thanks!! I have it like this already. Still having the error.
> 
> When is building I can see UnityFrameworks builds first and it fails with the error at last when the build is almost finished.
> 
> Thanks!!

Same error? It's working only on real device

**Comment by ArnauKokoro** [comment]
Yes, that was it. I was trying to build it with the simulator selected.

Many thanks!!

**Comment by marcel-mintouge** [comment]
Does this still only work on real devices and not in the simulator?

**Comment by ahmetardal** [comment]
@marcel-mintouge It works on real devices.

**Comment by abedolinger** [comment]
I was having this problem after confirming the recommendations above were already in place.  In my case, my Build Order setting had somehow been set to Dependency Order.  It has to be on Manual Order as below:
![xcode-manual-order](https://github.com/asmadsen/react-native-unity-view/assets/46080343/b5dc2144-569f-4df1-8a49-f623de874b54)
